import type { SymbolData, ChecklistItem } from '../types';

export const API_BASE = import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8000';

export const SYMBOLS_DATA: SymbolData[] = [
  { s: 'SPY', n: 'S&P 500 ETF', cats: ['indices', 'stocks'] },
  { s: 'QQQ', n: 'Nasdaq ETF', cats: ['indices', 'stocks'] },
  { s: 'DIA', n: 'Dow Jones ETF', cats: ['indices', 'stocks'] },
  { s: 'IWM', n: 'Russell 2000 ETF', cats: ['indices', 'stocks'] },
  { s: 'XLF', n: 'Financial Sector ETF', cats: ['stocks'] },
  { s: 'XLK', n: 'Technology Sector ETF', cats: ['stocks'] },
  { s: 'NQ=F', n: 'Nasdaq 100 Futures', cats: ['indices', 'futures'] },
  { s: 'ES=F', n: 'S&P 500 Futures', cats: ['indices', 'futures'] },
  { s: 'YM=F', n: 'Dow Jones Futures', cats: ['indices', 'futures'] },
  { s: 'RTY=F', n: 'Russell 2000 Futures', cats: ['indices', 'futures'] },
  { s: 'NIFTY50=F', n: 'Nifty 50 Futures', cats: ['indices', 'futures'] },
  { s: 'AAPL', n: 'Apple Inc.', cats: ['stocks'] },
  { s: 'TSLA', n: 'Tesla Inc.', cats: ['stocks'] },
  { s: 'NVDA', n: 'NVIDIA Corp.', cats: ['stocks'] },
  { s: 'MSFT', n: 'Microsoft Corp.', cats: ['stocks'] },
  { s: 'AMZN', n: 'Amazon.com Inc.', cats: ['stocks'] },
  { s: 'META', n: 'Meta Platforms', cats: ['stocks'] },
  { s: 'GOOGL', n: 'Alphabet Inc.', cats: ['stocks'] },
  { s: 'RELIANCE.NS', n: 'Reliance Industries', cats: ['stocks'] },
  { s: 'TCS.NS', n: 'Tata Consultancy Services', cats: ['stocks'] },
  { s: 'HDFCBANK.NS', n: 'HDFC Bank', cats: ['stocks'] },
  { s: 'INFY.NS', n: 'Infosys Ltd', cats: ['stocks'] },
  { s: 'GC=F', n: 'Gold Futures', cats: ['futures'] },
  { s: 'SI=F', n: 'Silver Futures', cats: ['futures'] },
  { s: 'CL=F', n: 'Crude Oil Futures', cats: ['futures'] },
  { s: 'NG=F', n: 'Natural Gas Futures', cats: ['futures'] },
  { s: 'HG=F', n: 'Copper Futures', cats: ['futures'] },
  { s: 'PL=F', n: 'Platinum Futures', cats: ['futures'] },
  { s: 'PA=F', n: 'Palladium Futures', cats: ['futures'] },
  { s: 'ZC=F', n: 'Corn Futures', cats: ['futures'] },
  { s: 'ZW=F', n: 'Wheat Futures', cats: ['futures'] },
  { s: 'ZS=F', n: 'Soybean Futures', cats: ['futures'] },
  { s: 'MNQ=F', n: 'Micro Nasdaq', cats: ['futures'] },
  { s: 'MES=F', n: 'Micro S&P 500', cats: ['futures'] },
  { s: 'MYM=F', n: 'Micro Dow', cats: ['futures'] },
  { s: 'M2K=F', n: 'Micro Russell 2000', cats: ['futures'] },
  { s: 'MGC=F', n: 'Micro Gold', cats: ['futures'] },
  { s: 'MCL=F', n: 'Micro Crude Oil', cats: ['futures'] },
  { s: 'MSI=F', n: 'Micro Silver', cats: ['futures'] },
  { s: 'ZB=F', n: 'US T-Bond Futures', cats: ['futures'] },
  { s: 'ZN=F', n: '10-Year T-Note Futures', cats: ['futures'] },
  { s: 'ZF=F', n: '5-Year T-Note Futures', cats: ['futures'] },
  { s: 'EURUSD=X', n: 'Euro / US Dollar', cats: ['forex'] },
  { s: 'GBPUSD=X', n: 'British Pound / USD', cats: ['forex'] },
  { s: 'JPYUSD=X', n: 'Japanese Yen / USD', cats: ['forex'] },
  { s: 'AUDUSD=X', n: 'Australian Dollar / USD', cats: ['forex'] },
  { s: 'USDCAD=X', n: 'US Dollar / Canadian', cats: ['forex'] },
  { s: 'NZDUSD=X', n: 'NZ Dollar / USD', cats: ['forex'] },
  { s: 'USDCHF=X', n: 'US Dollar / Swiss Franc', cats: ['forex'] },
  { s: 'USDMXN=X', n: 'US Dollar / Mexican Peso', cats: ['forex'] },
  { s: 'USDJPY=X', n: 'US Dollar / Japanese Yen', cats: ['forex'] },
  { s: 'BTC-USD', n: 'Bitcoin / USD', cats: ['crypto'] },
  { s: 'ETH-USD', n: 'Ethereum / USD', cats: ['crypto'] },
  { s: 'SOL-USD', n: 'Solana / USD', cats: ['crypto'] },
  { s: 'BNB-USD', n: 'BNB / USD', cats: ['crypto'] },
  { s: 'XRP-USD', n: 'XRP / USD', cats: ['crypto'] },
  { s: 'ADA-USD', n: 'Cardano / USD', cats: ['crypto'] },
  { s: 'DOGE-USD', n: 'Dogecoin / USD', cats: ['crypto'] },
  { s: 'DOT-USD', n: 'Polkadot / USD', cats: ['crypto'] },
  { s: 'LINK-USD', n: 'Chainlink / USD', cats: ['crypto'] },
  { s: 'AVAX-USD', n: 'Avalanche / USD', cats: ['crypto'] },
  { s: 'MATIC-USD', n: 'Polygon / USD', cats: ['crypto'] },
];

export const CATEGORIES = ['all', 'indices', 'stocks', 'futures', 'forex', 'crypto', 'dashboard', 'journal', 'heatmap', 'statistics', 'levels', 'setups', 'settings', 'calendar', 'news', 'scanner'];

export const CAT_LABELS: Record<string, string> = {
  all: 'ALL',
  indices: 'INDICES',
  stocks: 'STOCKS',
  futures: 'FUTURES',
  forex: 'FOREX',
  crypto: 'CRYPTO',
  dashboard: 'DASHBOARD',
  journal: 'JOURNAL',
  heatmap: 'HEATMAP',
  statistics: 'STATISTICS',
  levels: 'LEVELS',
  setups: 'SETUPS',
  settings: 'SETTINGS',
  calendar: 'CALENDAR',
  news: 'NEWS FEED',
  scanner: 'SCANNER',
};

export const SPECIAL_TABS: Record<string, number> = { calendar: 1, news: 1, scanner: 1, dashboard: 1, journal: 1, heatmap: 1, levels: 1, setups: 1, settings: 1, statistics: 1 };

export const CHECKLIST_ITEMS: ChecklistItem[] = [
  { key: 'market_structure', icon: 'chart', label: 'MARKET STRUCTURE', sub: 'BOS / CHoCH Confirmed' },
  { key: 'liquidity_sweep', icon: 'wave', label: 'LIQUIDITY SWEEP', sub: 'BSL / SSL Swept' },
  { key: 'order_block', icon: 'trend', label: 'ORDER BLOCK', sub: 'Valid OB at Entry' },
  { key: 'fair_value_gap', icon: 'zap', label: 'FAIR VALUE GAP', sub: 'Unmitigated FVG Present' },
  { key: 'killzone', icon: 'branch', label: 'KILLZONE', sub: 'London / NY Prime Time' },
  { key: 'premium_discount', icon: 'target', label: 'PREMIUM / DISCOUNT', sub: 'Price in Correct Zone' },
  { key: 'ote_retracement', icon: 'link', label: 'OTE RETRACEMENT', sub: '62-79% Fibonacci OTE' },
  { key: 'draw_on_liquidity', icon: 'compass', label: 'DRAW ON LIQUIDITY', sub: 'Clear BSL / SSL Target' },
];

export const WS_REFRESH = 30000;
export const NEWS_REFRESH = 60000;
